### ISSUE TITLE
Using only latitude and longitude characters in decimal degrees.

### ISSUE THREAD

**Issue by lefcgis** [rhlt/leaflet-geolet#1]
I want to use decimal degrees (not minutes, seconds and compass directions). I read the [Geolet Readme](https://github.com/rhlt/leaflet-geolet) (fomatSymbols and formatLatLng), 

![image](https://github.com/rhlt/leaflet-geolet/assets/13573242/18853bd0-0d09-4277-bc72-c34b6e6c23f4)

I couldn't do it. Please, can you teach me the steps to change it? This is my code. Thank you!

//Browser support test
	L.Geolet.browserSupport = !!(navigator && navigator.geolocation && navigator.geolocation.watchPosition);
	
	//Format coordinates (for use in the default pop up)
	L.Geolet.formatSymbols = {};
	L.Geolet.formatLatLng = function (latLng, l, a) {
		
		latLng = L.latLng(latLng, l, a);
		if (!latLng)
			return;
		
		var result = [];
		var symbols = _merge({ deg: '&deg;', min: '&#8217;', sec: '&#8221;', N: 'N', E: 'E', S: 'S', W: 'W', space: ' ', comma: ', ' }, L.Geolet.formatSymbols);
		
		['lat', 'lng'].forEach(function (key) {
			var dir = (key == 'lat' ? (latLng[key] < 0 ? symbols.S : symbols.N) : (latLng[key] < 0 ? symbols.W : symbols.E));
			var val = Math.round(Math.abs(latLng[key]) * 3600) / 3600;
			var deg = Math.floor(val)             + symbols.deg;
			var min = Math.floor(val *   60) % 60 + symbols.min;
			var sec = Math.floor(val * 3600) % 60 + symbols.sec;
			result.push([deg, min, sec, dir].join(symbols.space));
		});
		
		return result.join(symbols.comma);
	};
	
	//Factory function
	L.geolet = function (options) {
		return new L.Geolet(options);
	};
	
})()

**Comment by rhlt** [comment]
I'm not sure I understand. The code you're quoting is my code, and that's a helper function that converts raw data to degrees/minutes/seconds and compass directions. So if you're using that function, you can simply remove it and use the raw data directly. So instead of this: `L.Geolet.formatLatLng(latLng)`, use something like: `latLng.lat + ', ' + latLng.lng`. That will give you a string that uses decimals instead.

If you want to change the default text of the popup that shows when you click the location, you can use the `popupContent` option to pass a function that will generate a different text. If you've followed the readme, you will have put a line like `L.geolet({ position: 'bottomleft' }).addTo(map);` in your own code, to load Geolet. That's where you add options, like so:

```
L.geolet({
    position: 'bottomleft',
    popupContent: function (latLng) {
        // This will be called whenever the popup needs updating
        return latLng.lat + ', ' + latLng.lng;
    }
}).addTo(map);
```

I hope that helps!
